// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU7m1xfJ3GMX825i8c5AYL3lW5xhanReE',
    appId: '1:305259387485:web:71b31c5b233cfb65f24bb4',
    messagingSenderId: '305259387485',
    projectId: 'green-guard-app',
    authDomain: 'green-guard-app.firebaseapp.com',
    storageBucket: 'green-guard-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU3hzEZr1wrMHIYWL3CGJvoBLyIwpRTRg',
    appId: '1:305259387485:android:29379a53d85929fff24bb4',
    messagingSenderId: '305259387485',
    projectId: 'green-guard-app',
    storageBucket: 'green-guard-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUGgIrmrPLs8wNfHMlvBqm4HRKiH3SCAI',
    appId: '1:305259387485:ios:0b45f10522146577f24bb4',
    messagingSenderId: '305259387485',
    projectId: 'green-guard-app',
    storageBucket: 'green-guard-app.firebasestorage.app',
    iosBundleId: 'com.example.greenGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUGgIrmrPLs8wNfHMlvBqm4HRKiH3SCAI',
    appId: '1:305259387485:ios:0b45f10522146577f24bb4',
    messagingSenderId: '305259387485',
    projectId: 'green-guard-app',
    storageBucket: 'green-guard-app.firebasestorage.app',
    iosBundleId: 'com.example.greenGuard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU7m1xfJ3GMX825i8c5AYL3lW5xhanReE',
    appId: '1:305259387485:web:70f862e6cfaeae12f24bb4',
    messagingSenderId: '305259387485',
    projectId: 'green-guard-app',
    authDomain: 'green-guard-app.firebaseapp.com',
    storageBucket: 'green-guard-app.firebasestorage.app',
  );
}
